[package]
name = "y2kx-player"
version = "0.1.0"
edition = "2024"

license = "GPL-3.0-or-later"

[dependencies]
y2kx = { path = "../y2kx" }
clap = { version = "4.6", features = [ "derive" ] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62", features = [
    "Win32_UI_Input_KeyboardAndMouse",
] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
input-linux = "0.7"
#evdev = "0.13"
#uinput = "0.1"

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.25"